version: '3'
services:
  postgres:
    build: .
    image: library/postgres:11-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: practice
      POSTGRES_PASSWORD: admin